export type TourStep = { target: string; title: string; body: string; tip?: string };
export type TourModule = "coverage" | "predictions" | "highlights";
export const MODULE_TOURS: Record<TourModule, TourStep[]> = {
  coverage: [
    { target: "coverage-settings", title: "Choose what the model can see", body: "Pick a saved model and input cutoff: the snap, or a short time after it. These buttons change the saved prediction. Playing the field animation does not.", tip: "This source includes selected pass-coverage players, not all 22 players or pre-snap frames." },
    { target: "coverage-library", title: "Find a play", body: "Search teams and weeks, then filter by down, distance or result. Select a row to open its tracking. On a phone, use Show play library to reveal the list.", tip: "The error gallery deliberately selects mistakes; it is not a random sample." },
    { target: "coverage-field", title: "Watch the movement", body: "Play, pause or drag the time slider. Circles are passers and route runners; blue crosses are coverage defenders. Select a player to inspect them, or expand the field.", tip: "Only players included in the released tracking are drawn. The source has no ball, linemen or rushers." },
    { target: "coverage-evidence", title: "Read prediction and label separately", body: "Man and Zone probabilities are the model output. The released coverage label is the dataset comparison. Abstained means confidence is below the saved cutoff, so the model does not accept the prediction.", tip: "A disagreement is a model error against the released label; the label is not guaranteed ground truth." },
    { target: "coverage-evidence", title: "Inspect why, then test the claim", body: "Read the evidence and How was this calculated? Open Similar plays or Errors to inspect other cases. The evaluation page shows performance and limits across games.", tip: "Geometric pairings describe player movement; they do not prove the defensive assignment or the cause of a result." },
  ],
  predictions: [
    { target: "prediction-selectors", title: "Pick a historical matchup", body: "Choose a season and week, then select a game in the row below. The helmets and team names identify the selected away and home teams.", tip: "These are reconstructed historical backtests. The live forecast log is separate." },
    { target: "prediction-probabilities", title: "Read the win chances", body: "The two percentages are the model's chances for each team. The Elo baseline below is a simpler comparison. A 70% chance still leaves a 30% chance for the other team.", tip: "This model has no established gain over Elo. One game cannot show whether it is a better model." },
    { target: "prediction-breakdown", title: "Follow the calculation", body: "Start at Elo, then follow the feature rows to the final probability. Each bar changes log-odds, a scale used by the model; the running win probability beside it is easier to read.", tip: "The bars are not percentage-point changes and do not show that a feature caused the game result." },
    { target: "prediction-method", title: "Check the input cutoff", body: "Open How was this calculated? for the model version, prior-game inputs, quarterback assumption and missing data. The prediction cutoff is 24 hours before kickoff.", tip: "The quarterback shown is a scenario based on the previous game, not a confirmed lineup." },
    { target: "prediction-results", title: "Compare with what happened", body: "The final score is shown only as an observed result. Follow the performance link for log loss, Brier score and calibration: whether reported win chances match long-run outcomes.", tip: "Final scores are comparison data, not inputs to these pregame predictions." },
  ],
  highlights: [
    { target: "highlight-settings", title: "Choose a game and ranking model", body: "Pick a source game and a saved model. The reel budget changes the selected timeline blocks. Candidate cards currently come from the saved 3-minute reel.", tip: "This system ranks agreement with editorial highlight selection. It does not classify touchdowns or interceptions." },
    { target: "highlight-candidates", title: "Select a moment to play", body: "Click a candidate card to open its source interval in the player above. Replay starts it again; Next moves to another candidate. The player pauses at the interval's end.", tip: "These are short ranking windows, not verified full-play clip boundaries." },
    { target: "highlight-player", title: "Watch the source film", body: "Use the video controls to play or pause. If your browser blocks the first attempt, press Play interval again. If the video owner disables embedding, the source link opens the selected timestamp on YouTube.", tip: "Playback uses the official YouTube player. The site does not host broadcast footage." },
    { target: "highlight-signals", title: "Follow the evidence cursor", body: "The model-rank line and audio-loudness line are separate saved signals. The cursor follows video time. Blue editorial labels are shown only for evaluation, not as model inputs.", tip: "Rank 90 is a high position within this game, not a 90% chance. This graph does not prove which signal caused the model's score." },
    { target: "highlight-review", title: "Inspect misses and compare models", body: "Evidence shows saved scores and commentary. Missed moments shows editorial segments the reel left out. Review supports human inspection; the methodology and benchmark below explain how the system was evaluated.", tip: "Timestamp mapping uses the dataset's trim offset and has not been independently checked frame by frame." },
  ],
};
