"""ffprobe/ffmpeg helpers. Commands are argument lists (never shell strings) and every path is generated by the service."""
from __future__ import annotations

import json
import shutil
import subprocess
import wave
from pathlib import Path

import numpy as np

CLIP_S, RATE = 2.0, 16000


class MediaError(ValueError):
    pass


def available() -> bool:
    return shutil.which("ffmpeg") is not None and shutil.which("ffprobe") is not None


def probe(path: Path) -> dict:
    """Real container facts from ffprobe; the file extension is never trusted."""
    r = subprocess.run(["ffprobe", "-v", "error", "-print_format", "json", "-show_format", "-show_streams", str(path)], capture_output=True, text=True, check=False, timeout=60)
    if r.returncode != 0:
        raise MediaError("The file could not be read as audio or video. It may be truncated or in an unsupported format.")
    info = json.loads(r.stdout or "{}")
    streams = info.get("streams", [])
    v = next((s for s in streams if s.get("codec_type") == "video"), None)
    a = next((s for s in streams if s.get("codec_type") == "audio"), None)
    try:
        duration = float(info["format"]["duration"])
    except (KeyError, ValueError) as e:
        raise MediaError("The file has no readable duration. It may be truncated.") from e
    return {"duration_s": duration, "has_video": v is not None, "has_audio": a is not None, "width": v and v.get("width"), "height": v and v.get("height"),
            "video_codec": v and v.get("codec_name"), "audio_codec": a and a.get("codec_name"), "format": info["format"].get("format_name")}


def run(cmd: list[str], cancelled=None, timeout: float = 3600) -> None:
    """Run ffmpeg; poll so a cancelled job stops the process instead of finishing it."""
    p = subprocess.Popen(cmd, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)
    waited = 0.0
    while True:
        try:
            p.wait(timeout=0.5)
            break
        except subprocess.TimeoutExpired:
            waited += 0.5
            if (cancelled is not None and cancelled()) or waited > timeout:
                p.kill()
                p.wait()
                raise MediaError("cancelled" if waited <= timeout else "Processing timed out.") from None
    if p.returncode != 0:
        raise MediaError("ffmpeg could not process this file: " + (p.stderr.read() or "")[-300:].strip())


def extract_audio(src: Path, wav: Path, cancelled=None) -> None:
    run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(src), "-vn", "-ac", "1", "-ar", str(RATE), "-c:a", "pcm_s16le", str(wav)], cancelled)


def loudness_db(wav: Path) -> np.ndarray:
    """RMS level in dB per 2-second clip, including a final partial clip of at least half a second."""
    with wave.open(str(wav), "rb") as w:
        n, out = int(CLIP_S * RATE), []
        while True:
            buf = w.readframes(n)
            if len(buf) < RATE:                                             # under 0.5 s left
                break
            x = np.frombuffer(buf, dtype=np.int16).astype(np.float64) / 32768.0
            out.append(20 * np.log10(max(float(np.sqrt(np.mean(x * x))), 1e-6)))
    return np.array(out, np.float32)


def cut(src: Path, dest: Path, start_s: float, end_s: float, has_video: bool, cancelled=None) -> None:
    """Re-encode so the cut is exact (keyframe copies drift by up to a GOP)."""
    codec = ["-c:v", "libx264", "-preset", "veryfast", "-crf", "23", "-pix_fmt", "yuv420p", "-c:a", "aac", "-movflags", "+faststart"] if has_video else ["-vn", "-c:a", "aac"]
    run(["ffmpeg", "-y", "-loglevel", "error", "-ss", f"{start_s:.3f}", "-i", str(src), "-t", f"{end_s - start_s:.3f}", *codec, str(dest)], cancelled)


def concat(parts: list[Path], dest: Path, listing: Path, cancelled=None) -> None:
    listing.write_text("".join(f"file '{p.name}'\n" for p in parts))
    run(["ffmpeg", "-y", "-loglevel", "error", "-f", "concat", "-safe", "0", "-i", str(listing), "-c", "copy", "-movflags", "+faststart", str(dest)], cancelled)
