"""ffprobe/ffmpeg helpers. Commands are argument lists (never shell strings) and every path is generated by the service."""
from __future__ import annotations

import json
import shutil
import subprocess
import wave
from pathlib import Path

import numpy as np

CLIP_S, RATE = 2.0, 16000


class MediaError(ValueError):
    pass


def available() -> bool:
    return shutil.which("ffmpeg") is not None and shutil.which("ffprobe") is not None


def probe(path: Path) -> dict:
    """Real container facts from ffprobe; the file extension is never trusted."""
    r = subprocess.run(["ffprobe", "-v", "error", "-print_format", "json", "-show_format", "-show_streams", str(path)], capture_output=True, text=True, check=False, timeout=60)
    if r.returncode != 0:
        raise MediaError("The file could not be read as audio or video. It may be truncated or in an unsupported format.")
    info = json.loads(r.stdout or "{}")
    streams = info.get("streams", [])
    v = next((s for s in streams if s.get("codec_type") == "video"), None)
    a = next((s for s in streams if s.get("codec_type") == "audio"), None)
    try:
        duration = float(info["format"]["duration"])
    except (KeyError, ValueError) as e:
        raise MediaError("The file has no readable duration. It may be truncated.") from e
    sd = lambda st: float(st["duration"]) if st and st.get("duration") not in (None, "N/A") else None
    origin = float(info["format"].get("start_time") or 0)
    audio_start = max(0.0, float(a.get("start_time") or origin) - origin) if a else None
    fps = None
    if v and v.get("r_frame_rate") and "/" in v["r_frame_rate"]:
        n, d = v["r_frame_rate"].split("/")
        fps = float(n) / float(d) if float(d) else None
    return {"duration_s": duration, "video_duration_s": sd(v), "audio_duration_s": sd(a), "audio_start_s": audio_start, "fps": fps, "has_video": v is not None, "has_audio": a is not None, "width": v and v.get("width"), "height": v and v.get("height"),
            "video_codec": v and v.get("codec_name"), "audio_codec": a and a.get("codec_name"), "format": info["format"].get("format_name")}


def run(cmd: list[str], cancelled=None, timeout: float = 3600) -> None:
    """Run ffmpeg; poll so a cancelled job stops the process instead of finishing it."""
    p = subprocess.Popen(cmd, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)
    waited = 0.0
    while True:
        try:
            p.wait(timeout=0.5)
            break
        except subprocess.TimeoutExpired:
            waited += 0.5
            if (cancelled is not None and cancelled()) or waited > timeout:
                p.kill()
                p.wait()
                raise MediaError("cancelled" if waited <= timeout else "Processing timed out.") from None
    if p.returncode != 0:
        raise MediaError("ffmpeg could not process this file: " + (p.stderr.read() or "")[-300:].strip())


def extract_audio(src: Path, wav: Path, cancelled=None) -> None:
    run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(src), "-vn", "-ac", "1", "-ar", str(RATE), "-c:a", "pcm_s16le", str(wav)], cancelled)


def loudness_db(wav: Path) -> np.ndarray:
    """RMS level in dB per 2-second clip, including a final partial clip of at least half a second."""
    with wave.open(str(wav), "rb") as w:
        n, out = int(CLIP_S * RATE), []
        while True:
            buf = w.readframes(n)
            if len(buf) < RATE:                                             # under 0.5 s left
                break
            x = np.frombuffer(buf, dtype=np.int16).astype(np.float64) / 32768.0
            out.append(20 * np.log10(max(float(np.sqrt(np.mean(x * x))), 1e-6)))
    return np.array(out, np.float32)


def audio_bounds(wav: Path, bins: int, start_s: float = 0.0) -> dict:
    """Exact analysed bin bounds in uploaded-file seconds, including the last partial bin."""
    with wave.open(str(wav), "rb") as w:
        duration = w.getnframes() / w.getframerate()
    return {"audio_start_s": start_s, "audio_end_s": start_s + duration,
            "bin_start_s": [start_s + i * CLIP_S for i in range(bins)],
            "bin_end_s": [start_s + min((i + 1) * CLIP_S, duration) for i in range(bins)]}


def cut(src: Path, dest: Path, start_s: float, end_s: float, has_video: bool, cancelled=None) -> None:
    """Re-encode so the cut is exact (keyframe copies drift by up to a GOP)."""
    codec = ["-c:v", "libx264", "-preset", "veryfast", "-crf", "23", "-pix_fmt", "yuv420p", "-c:a", "aac", "-movflags", "+faststart"] if has_video else ["-vn", "-c:a", "aac"]
    run(["ffmpeg", "-y", "-loglevel", "error", "-ss", f"{start_s:.3f}", "-i", str(src), "-t", f"{end_s - start_s:.3f}", *codec, str(dest)], cancelled)


def reel(src: Path, dest: Path, spans: list[tuple[float, float]], budget_s: float, has_video: bool, fps: float | None, cancelled=None) -> None:
    """One encode of all spans in order, hard-limited so that no stream of the exported file runs past the budget.

    Concatenating separately encoded cuts adds a little per file (each cut ends on a whole video frame and a whole AAC frame),
    which is how a 180 s selection once rendered as 180.2 s. Here the spans are joined inside one filter graph and the output
    is cut one video frame short of the budget, so the container, video and audio durations are all at or under it.
    """
    cmd = ["ffmpeg", "-y", "-loglevel", "error"]
    for a, b in spans:
        cmd += ["-ss", f"{a:.3f}", "-t", f"{b - a:.3f}", "-i", str(src)]
    n = len(spans)
    limit = budget_s - (1.0 / fps if has_video and fps else 0.03)
    if has_video:
        graph = "".join(f"[{i}:v:0][{i}:a:0]" for i in range(n)) + f"concat=n={n}:v=1:a=1[v][a]"
        cmd += ["-filter_complex", graph, "-map", "[v]", "-map", "[a]", "-t", f"{limit:.3f}", "-c:v", "libx264", "-preset", "veryfast", "-crf", "23", "-pix_fmt", "yuv420p", "-c:a", "aac", "-movflags", "+faststart", str(dest)]
    else:
        graph = "".join(f"[{i}:a:0]" for i in range(n)) + f"concat=n={n}:v=0:a=1[a]"
        cmd += ["-filter_complex", graph, "-map", "[a]", "-t", f"{limit:.3f}", "-c:a", "aac", str(dest)]
    run(cmd, cancelled)
